services:
  headscale:
    image: headscale/headscale:0.23.0
    container_name: headscale
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50443:50443"
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    command: [ "serve" ]
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - postgres

  headscale-hub:
    image: headscale-hub
    container_name: headscale-hub
    restart: always
    build:
      context: ./hub/
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./hub:/hub
    command: ["headscale-hub", "-c", "/hub/config.yml" ]
    depends_on:
      - postgres

  headscale-ui:
    image: headscale-hub-ui
    container_name: headscale-hub-ui
    restart: always
    build:
      context: ./hub-ui
      dockerfile: Dockerfile
    ports:
      - "8089:80"

  # sqlite-web:
  #   image: coleifer/sqlite-web
  #   container_name: sqlite-web
  #   ports:
  #     - "8090:8080"
  #   volumes:
  #     - ./headscale/data:/data
  #   environment:
  #     - SQLITE_DATABASE=db.sqlite

  postgres:
    image: postgres:13.16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: headscale
      POSTGRES_PASSWORD: headscale
      POSTGRES_DB: headscale
    volumes:
      - ./data:/var/lib/postgresql/data